// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var View;
    View = (function(_super) {

      __extends(View, _super);

      function View() {
        return View.__super__.constructor.apply(this, arguments);
      }

      View.prototype.template = _.template('<li>\n  <a href=\'/locations/<%= id %>\'>\n    <span class=\'name\'><%= name %> \n  </a>\n</li>');

      View.prototype.initialize = function() {
        _.bindAll(this);
        return this.model.on('change', this.render);
      };

      View.prototype.render = function(done) {
        var content;
        content = this.template(this.model.toJSON());
        this.$el.html(content);
        if (typeof done === "function") {
          done(this.el);
        }
        return this;
      };

      return View;

    })(Backbone.View);
    return View;
  });

}).call(this);
