// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone', 'locations/collections/locations', 'locations/views/list'], function($, Backbone, Locations, LocationsListView) {
    var Router;
    Router = (function(_super) {

      __extends(Router, _super);

      function Router() {
        return Router.__super__.constructor.apply(this, arguments);
      }

      Router.prototype.initialize = function() {
        var collection, view;
        console.log('home');
        collection = new Locations;
        view = new LocationsListView({
          collection: collection
        });
        view.render(function(el) {
          return $('#side').html(el);
        });
        return collection.fetch();
      };

      return Router;

    })(Backbone.Router);
    return Router;
  });

}).call(this);
