// Generated by CoffeeScript 1.3.3
(function() {

  requirejs(['jquery', 'backbone', 'routers/main', 'locations/routers/main'], function($, Backbone, MainAppRouter, LocationsRouter) {
    var _ref;
    new LocationsRouter;
    new MainAppRouter;
    if ((_ref = Backbone.history) != null) {
      _ref.start({
        pushState: true
      });
    }
    return $(document).on("click", "a:not([data-bypass])", function(evt) {
      var href, root;
      href = $(this).prop("href");
      root = location.protocol + "//" + location.host;
      if (href) {
        evt.preventDefault();
      }
      return Backbone.history.navigate(href.slice(root.length), true);
    });
  });

}).call(this);
